version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - vscode-extension:/root/.vscode-server
      - vscode-extension-insiders:/root/.vscode-server-insiders
    command: sleep infinity
    network_mode: service:db
    environment:
      - MIX_ENV=dev
      - DATABASE_URL=ecto://postgres:postgres@localhost/app_dev

  db:
    image: postgres:18-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
  vscode-extension:
  vscode-extension-insiders:
